import type { CarHire } from "@/lib/data/car-hires";
import type { SavedPlan } from "@/lib/saved-trips";

function pad(n: number) {
  return String(n).padStart(2, "0");
}

/** Format as YYYYMMDD for all-day calendar events */
export function toYmd(date: Date) {
  return `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}`;
}

export function addDays(date: Date, days: number) {
  const d = new Date(date);
  d.setDate(d.getDate() + days);
  return d;
}

export function planToPlainText(
  plan: SavedPlan,
  meta: {
    startDate: string;
    partySize: number;
    transportLabel?: string;
    carHires?: CarHire[];
  },
) {
  const lines: string[] = [
    plan.title,
    "",
    plan.summary,
    "",
    `Recommended stay: ${plan.recommendedStay}`,
    `Party size: ${meta.partySize}`,
    `Start date: ${meta.startDate}`,
  ];

  if (meta.transportLabel) {
    lines.push(`Transport: ${meta.transportLabel}`);
  }

  if (plan.budgetBreakdown) {
    lines.push(
      "",
      "Damage cost estimate",
      `Total: ~KES ${plan.budgetBreakdown.totalKes.toLocaleString()}`,
      `Lodging: KES ${plan.budgetBreakdown.lodgingKes.toLocaleString()}`,
      `Activities: KES ${plan.budgetBreakdown.activitiesKes.toLocaleString()}`,
      `Food: KES ${plan.budgetBreakdown.foodKes.toLocaleString()}`,
      `Transport: KES ${plan.budgetBreakdown.transportKes.toLocaleString()}`,
      `Contingency: KES ${plan.budgetBreakdown.contingencyKes.toLocaleString()}`,
      plan.budgetBreakdown.notes,
    );
  }

  for (const day of plan.days) {
    lines.push(
      "",
      `Day ${day.day}: ${day.theme}`,
      `Morning: ${day.morning}`,
      `Afternoon: ${day.afternoon}`,
      `Evening: ${day.evening}`,
      `Food: ${day.foodTip}`,
      `Transport: ${day.transportTip}`,
      day.estimatedDayCostKes != null
        ? `Est. day cost: ~KES ${day.estimatedDayCostKes.toLocaleString()}`
        : "",
    );
  }

  if (meta.carHires && meta.carHires.length > 0) {
    lines.push("", "Car hire & airport pickup contacts");
    for (const c of meta.carHires) {
      lines.push(
        `${c.name} — ${c.phoneDisplay} — ${c.websiteUrl} (${c.areas})`,
      );
    }
  }

  if (plan.packingTips?.length) {
    lines.push("", "Packing", ...plan.packingTips.map((t) => `- ${t}`));
  }
  if (plan.localEtiquette?.length) {
    lines.push(
      "",
      "Local etiquette",
      ...plan.localEtiquette.map((t) => `- ${t}`),
    );
  }

  lines.push("", "Generated by Swahili Trail");
  return lines.filter((l) => l !== undefined).join("\n");
}

export function downloadTextFile(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function icsEscape(text: string) {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/\n/g, "\\n")
    .replace(/,/g, "\\,")
    .replace(/;/g, "\\;");
}

export function planToIcs(
  plan: SavedPlan,
  startDate: Date,
  options?: { transportLabel?: string },
) {
  const stamp = toYmd(new Date()) + "T120000Z";
  const events = plan.days.map((day) => {
    const dayStart = addDays(startDate, day.day - 1);
    const dayEnd = addDays(startDate, day.day);
    const desc = [
      day.morning,
      day.afternoon,
      day.evening,
      `Food: ${day.foodTip}`,
      `Transport: ${day.transportTip}`,
      options?.transportLabel ? `Hire: ${options.transportLabel}` : "",
    ]
      .filter(Boolean)
      .join("\n");

    return [
      "BEGIN:VEVENT",
      `UID:swahili-trail-${day.day}-${dayStart.getTime()}@swahilitrail`,
      `DTSTAMP:${stamp}`,
      `DTSTART;VALUE=DATE:${toYmd(dayStart)}`,
      `DTEND;VALUE=DATE:${toYmd(dayEnd)}`,
      `SUMMARY:${icsEscape(`Day ${day.day}: ${day.theme}`)}`,
      `DESCRIPTION:${icsEscape(desc)}`,
      "END:VEVENT",
    ].join("\r\n");
  });

  return [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Swahili Trail//Trip Planner//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    `X-WR-CALNAME:${icsEscape(plan.title)}`,
    ...events,
    "END:VCALENDAR",
  ].join("\r\n");
}

export function downloadIcs(filename: string, ics: string) {
  const blob = new Blob([ics], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/** Google Calendar template for an all-day multi-day span */
export function googleCalendarUrl(
  plan: SavedPlan,
  startDate: Date,
): string {
  const end = addDays(startDate, plan.days.length);
  const details = [
    plan.summary,
    "",
    `Stay: ${plan.recommendedStay}`,
    plan.budgetBreakdown
      ? `Est. total: KES ${plan.budgetBreakdown.totalKes.toLocaleString()}`
      : "",
    "",
    ...plan.days.map(
      (d) =>
        `Day ${d.day} — ${d.theme}\n${d.morning} / ${d.afternoon} / ${d.evening}`,
    ),
  ]
    .filter(Boolean)
    .join("\n");

  const params = new URLSearchParams({
    action: "TEMPLATE",
    text: plan.title,
    dates: `${toYmd(startDate)}/${toYmd(end)}`,
    details: details.slice(0, 1800),
    location: "Mombasa, Kenya",
  });
  return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

/** Outlook web compose for the trip window */
export function outlookCalendarUrl(plan: SavedPlan, startDate: Date): string {
  const end = addDays(startDate, plan.days.length);
  const params = new URLSearchParams({
    path: "/calendar/action/compose",
    rru: "addevent",
    subject: plan.title,
    startdt: startDate.toISOString().slice(0, 10),
    enddt: end.toISOString().slice(0, 10),
    body: plan.summary,
    location: "Mombasa, Kenya",
  });
  return `https://outlook.live.com/calendar/0/deeplink/compose?${params.toString()}`;
}
